import { describe, expect, it } from 'vitest';
import type { ExtractedUnzenDefinition } from '../src/source-transform';
import {
  generateUnzenTypeDeclarations,
  UnzenTypeGenerationError,
} from '../src/type-declarations';

function definition(
  name: string,
  parameters: ExtractedUnzenDefinition['parameters'],
  returnType: string,
  fileName = `/src/${name}.ts`,
): ExtractedUnzenDefinition {
  return {
    name,
    fileName,
    line: 3,
    column: 1,
    typeParameters: [],
    parameters,
    returnType,
  };
}

describe('generateUnzenTypeDeclarations', () => {
  it('renders a deterministic typed client schema sorted by function name', () => {
    const declarations = generateUnzenTypeDeclarations([
      definition('sum', [
        { name: 'a', type: 'number', optional: false, rest: false },
        { name: 'b', type: 'number', optional: false, rest: false },
      ], 'number'),
      definition('slugify-text', [
        { name: 'value', type: 'string', optional: false, rest: false },
        { name: 'separator', type: 'string', optional: true, rest: false },
      ], 'string'),
    ]);

    expect(declarations).toBe(`/* Generated by @unzen/bundler. Do not edit. */

export type UnzenFunctions = {
  readonly "slugify-text": (value: string, separator?: string) => string;
  readonly "sum": (a: number, b: number) => number;
};

export type UnzenFunctionName = keyof UnzenFunctions;
export type UnzenFunctionArgs<Name extends UnzenFunctionName> =
  Parameters<UnzenFunctions[Name]>;
export type UnzenFunctionResult<Name extends UnzenFunctionName> =
  Awaited<ReturnType<UnzenFunctions[Name]>>;
export type TypedUnzenClient =
  import('@unzen/client').UnzenClient<UnzenFunctions>;
`);
  });

  it('preserves generic and rest signatures and supports an empty schema', () => {
    const generic = definition('identity', [
      { name: 'value', type: 'T', optional: false, rest: false },
      { name: 'rest', type: 'unknown[]', optional: false, rest: true },
    ], 'T');
    generic.typeParameters = ['T'];

    expect(generateUnzenTypeDeclarations([generic]))
      .toContain('readonly "identity": <T>(value: T, ...rest: unknown[]) => T;');
    expect(generateUnzenTypeDeclarations([])).toContain('export type UnzenFunctions = {\n};');
  });

  it('rejects duplicate public function names with both source locations', () => {
    const first = definition('sum', [], 'number', '/src/first.ts');
    const second = definition('sum', [], 'string', '/src/second.ts');

    expect(() => generateUnzenTypeDeclarations([first, second]))
      .toThrowError(UnzenTypeGenerationError);
    expect(() => generateUnzenTypeDeclarations([first, second]))
      .toThrow('/src/first.ts:3:1');
    expect(() => generateUnzenTypeDeclarations([first, second]))
      .toThrow('/src/second.ts:3:1');
  });

  it('rejects metadata that escapes the single generated function type', () => {
    const injected = definition('safe', [], 'number; export type Injected = string');

    expect(() => generateUnzenTypeDeclarations([injected]))
      .toThrow('invalid signature for "safe"');
  });
});
