/**
 * Core types for the Swarm Intelligence LLM module.
 *
 * Architecture concept (contrast with pipeline approach in ../types.ts):
 *   - Pipeline: 30B model split into 8 segments across nodes, central Coordinator
 *   - Swarm: Complete 1.2B model on each node, decentralized gossip coordination
 *
 * Each browser peer runs the full model independently. Quality emerges from
 * collective intelligence — multiple independent proposals are cross-evaluated
 * and the swarm converges on the best response via consensus.
 *
 * Key swarm intelligence principles applied:
 *   - Self-organization: Peers autonomously generate and evaluate proposals
 *   - Stigmergy: Shared scores act as "pheromone trails" guiding consensus
 *   - Emergence: Collective output quality exceeds individual model capability
 *   - Decentralization: No single coordinator; gossip-based state propagation
 *
 * Communication constraint (PLAN.md 1.2):
 *   All peer-to-peer messages are relayed through unzen infrastructure (no direct WebRTC).
 *   The relay is a "dumb pipe" — routing/scheduling intelligence lives in the peers.
 */

// --- Branded ID types ---

export type PeerId = string & { readonly __brand: 'PeerId' };
export type TaskId = string & { readonly __brand: 'TaskId' };
export type ProposalId = string & { readonly __brand: 'ProposalId' };

export function peerId(id: string): PeerId {
  return id as PeerId;
}

export function taskId(id: string): TaskId {
  return id as TaskId;
}

export function proposalId(id: string): ProposalId {
  return id as ProposalId;
}

// --- Swarm configuration ---

/**
 * Configuration for swarm inference behavior.
 *
 * Design rationale for defaults:
 *   - minPeers=3: minimum for meaningful majority voting (2/3 consensus)
 *   - maxPeers=7: diminishing returns beyond this for 1.2B models; keeps
 *     evaluation cost manageable (N×N cross-evaluation)
 *   - consensusThreshold=0.6: supermajority not required; 60% agreement suffices
 *     because cross-evaluation scoring is continuous, not binary
 *   - proposalTimeoutMs=30000: 1.2B model generates ~50-100 tokens/sec on WebGPU;
 *     30s allows ~1500-3000 tokens, sufficient for most responses
 *   - evaluationTimeoutMs=10000: scoring a single candidate is faster than
 *     generating one (shorter input, single score output)
 */
export interface SwarmConfig {
  /** Minimum peers required to start swarm inference. Must be >= 2. */
  readonly minPeers: number;
  /** Maximum peers participating in one task. Must be >= minPeers. */
  readonly maxPeers: number;
  /** Fraction of peers that must agree for consensus (0-1 exclusive of 0). */
  readonly consensusThreshold: number;
  /** Timeout for a peer to generate a proposal (ms). Must be > 0. */
  readonly proposalTimeoutMs: number;
  /** Timeout for a peer to evaluate a proposal (ms). Must be > 0. */
  readonly evaluationTimeoutMs: number;
}

export const DEFAULT_SWARM_CONFIG: SwarmConfig = {
  minPeers: 3,
  maxPeers: 7,
  consensusThreshold: 0.6,
  proposalTimeoutMs: 30_000,
  evaluationTimeoutMs: 10_000,
};

// --- Peer types ---

export enum PeerStatus {
  IDLE = 'idle',
  GENERATING = 'generating',
  EVALUATING = 'evaluating',
  DISCONNECTED = 'disconnected',
}

export interface PeerInfo {
  readonly id: PeerId;
  status: PeerStatus;
  /** Unix timestamp (ms) of last message received from this peer. */
  lastSeen: number;
  /**
   * Accumulated reliability score (0-1) based on historical behavior.
   * Peers that consistently deliver quality proposals and stay connected
   * earn higher scores, giving their votes more weight in consensus.
   */
  reliability: number;
}

// --- Proposal and evaluation types ---

/**
 * A candidate response generated by a single peer.
 * Each peer independently generates a proposal for the same prompt.
 */
export interface Proposal {
  readonly id: ProposalId;
  readonly taskId: TaskId;
  readonly peerId: PeerId;
  readonly text: string;
  readonly generationTimeMs: number;
}

/**
 * A peer's evaluation (score) of another peer's proposal.
 * Cross-evaluation is the core mechanism for quality emergence:
 * even weak models can identify relative quality among candidates.
 */
export interface Evaluation {
  readonly taskId: TaskId;
  /** Peer who performed this evaluation. */
  readonly evaluatorId: PeerId;
  /** Proposal being evaluated. */
  readonly proposalId: ProposalId;
  /** Score from 0 (worst) to 1 (best). */
  readonly score: number;
}

// --- Swarm inference result ---

/**
 * Final result from swarm inference.
 * The selected text is the proposal that achieved consensus.
 */
export interface SwarmResult {
  readonly taskId: TaskId;
  readonly text: string;
  /** Number of peers that participated. */
  readonly participantCount: number;
  /** Number of proposals generated. */
  readonly proposalCount: number;
  /** Consensus score of the winning proposal (0-1). */
  readonly consensusScore: number;
  /** Whether clear consensus was reached (score above threshold with separation). */
  readonly consensusReached: boolean;
  /** Total wall-clock time in milliseconds. */
  readonly totalTimeMs: number;
}
