/** Deterministic TypeScript declarations for extracted Unzen functions. */

import ts from 'typescript';
import type {
  ExtractedUnzenDefinition,
  ExtractedUnzenParameter,
} from './source-transform';

const SAFE_PARAMETER_NAME = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Build error raised when extracted definitions cannot form one public schema. */
export class UnzenTypeGenerationError extends Error {
  constructor(message: string) {
    super(`[unzen] ${message}`);
    this.name = 'UnzenTypeGenerationError';
  }
}

function sourceLocation(definition: ExtractedUnzenDefinition): string {
  return `${definition.fileName}:${definition.line}:${definition.column}`;
}

function compareDefinitions(
  left: ExtractedUnzenDefinition,
  right: ExtractedUnzenDefinition,
): number {
  if (left.name < right.name) return -1;
  if (left.name > right.name) return 1;
  return 0;
}

function renderParameter(parameter: ExtractedUnzenParameter, index: number): string {
  const name = SAFE_PARAMETER_NAME.test(parameter.name) ? parameter.name : `arg${index + 1}`;
  const rest = parameter.rest ? '...' : '';
  const optional = parameter.optional ? '?' : '';
  const type = parameter.type.trim() || (parameter.rest ? 'unknown[]' : 'unknown');
  return `${rest}${name}${optional}: ${type}`;
}

function renderSignature(definition: ExtractedUnzenDefinition): string {
  const typeParameters = definition.typeParameters.length > 0
    ? `<${definition.typeParameters.map((parameter) => parameter.trim()).join(', ')}>`
    : '';
  const parameters = definition.parameters.map(renderParameter).join(', ');
  const returnType = definition.returnType.trim() || 'unknown';
  return `${typeParameters}(${parameters}) => ${returnType}`;
}

/**
 * Validate the assembled function type as one TypeScript type alias. Besides
 * catching malformed optional/rest combinations, requiring exactly one AST
 * statement prevents manually supplied metadata from injecting declarations.
 */
function validateSignature(definition: ExtractedUnzenDefinition, signature: string): void {
  const candidate = `type __UnzenSignature = ${signature};`;
  const transpiled = ts.transpileModule(candidate, {
    reportDiagnostics: true,
    compilerOptions: { target: ts.ScriptTarget.ESNext },
  });
  const diagnostic = transpiled.diagnostics?.find(
    (entry) => entry.category === ts.DiagnosticCategory.Error,
  );
  const parsed = ts.createSourceFile(
    '__unzen_signature__.ts',
    candidate,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const statement = parsed.statements[0];
  if (
    diagnostic
    || parsed.statements.length !== 1
    || !statement
    || !ts.isTypeAliasDeclaration(statement)
    || !ts.isFunctionTypeNode(statement.type)
  ) {
    const detail = diagnostic
      ? `: ${ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')}`
      : '';
    throw new UnzenTypeGenerationError(
      `invalid signature for ${JSON.stringify(definition.name)} at `
      + `${sourceLocation(definition)}${detail}`,
    );
  }
}

/**
 * Render a standalone declaration module consumed as
 * `UnzenClient<UnzenFunctions>`. Output order is independent of module
 * traversal so rebuilds produce byte-identical declarations.
 */
export function generateUnzenTypeDeclarations(
  definitions: readonly ExtractedUnzenDefinition[],
): string {
  const byName = new Map<string, ExtractedUnzenDefinition>();
  for (const definition of definitions) {
    const existing = byName.get(definition.name);
    if (existing) {
      throw new UnzenTypeGenerationError(
        `duplicate function name ${JSON.stringify(definition.name)} at `
        + `${sourceLocation(existing)} and ${sourceLocation(definition)}`,
      );
    }
    byName.set(definition.name, definition);
  }

  const entries = [...byName.values()].sort(compareDefinitions).map((definition) => {
    const signature = renderSignature(definition);
    validateSignature(definition, signature);
    return `  readonly ${JSON.stringify(definition.name)}: ${signature};`;
  });
  const renderedEntries = entries.length > 0 ? `${entries.join('\n')}\n` : '';

  return `/* Generated by @unzen/bundler. Do not edit. */

export type UnzenFunctions = {
${renderedEntries}};

export type UnzenFunctionName = keyof UnzenFunctions;
export type UnzenFunctionArgs<Name extends UnzenFunctionName> =
  Parameters<UnzenFunctions[Name]>;
export type UnzenFunctionResult<Name extends UnzenFunctionName> =
  Awaited<ReturnType<UnzenFunctions[Name]>>;
export type TypedUnzenClient =
  import('@unzen/client').UnzenClient<UnzenFunctions>;
`;
}
